language: python
python:
 - "3.5"
branches:
  only:
    - master
install:
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install pytest pytest-cov
script:
    - py.test tests/
after_success:
    - coveralls
env:
 - FLASK_ENV=dev
