language: python
python:
 - "3.5"
branches:
  only:
    - master
install:
    - pip install -r requirements.txt
    - pip install -r testrequirements.txt
    - pip install coveralls
script:
    - py.test --cov-report=term-missing --cov=app tests/
after_success:
    - coveralls
env:
 - FLASK_ENV=dev
